language: objective-c
osx_image: xcode8.3

env:
  global:
    - secure: "IJwhvYOzGUTokHSfCRR6ioL5WrUoWAdzKJHeYfA7F6qY1SZCzTij7+tPLY61ANdjuZ+vTRvf1mtwObyMAsfo9jCtU65L234CG3c1Vun4xpzTCwk3K5PsSIP4S9tOJc0ddWoZWAD9cFZ4ZbSN0IApwRFX49BglsnyHYn/tCkODI04CqIpCsNJ2uBX9in9ShztXNBpIDaLoXSABAPco1EXUW//ydwjdt8GFESLVb8MRD0zbkymrgvCDQgOgsLWsT0GzQAXjzwXzpX6PQafc70UD/uPVtc8E5TlXuuXOqohqbzXtpcF8/lEqqZWZv2m4SkiDqFFVWU+2uvPbGiTWSDBIvxTL8QW9HXwKyijABh31v7dSiXwC/Mver9+MQ8nHRUP4U1rAft/VXMo/rXhiQoEuZRr1Dv8uctESGhafelKSvfIZSk1wZ92ltceP1fChn218pkEMVSuOdZxFeAFLgbC1rrLmofNUkhcaPq3dlzGe1xAzBjKB+wG+EKtGe/QnYNDQBFZ29iv31G54eAqZaDqyLqYrHRPMTwueEqJgufnlIbgUBov/Adob1FV0+MNxPY4kKysSWLBmiU+eW1swNkxbys4dLRZtTa2/sgU8sXSQBW+goHxTgKIS0jEqBzHXElizUhiF/LBS6UoWTvSJyapZvtYMAzP11c7ggQ3eJeB4KE="

branches:
  only:
  - master

script:
- brew install --verbose --build-bottle albertosottile/syncplay/pyside

before_install:
- brew update
- brew upgrade python
- which python3
- python3 --version
- which pip3
- pip3 --version

install:
- brew install --only-dependencies --verbose --build-bottle albertosottile/syncplay/pyside

after_success:
- brew test --verbose albertosottile/syncplay/pyside

before_deploy:
- brew bottle --verbose --root-url="https://dl.bintray.com/alby128/homebrew-syncplay" --json albertosottile/syncplay/pyside
- ls -al
- python3 bottle_mover.py
- ls -al

deploy:
  skip_cleanup: true
  on: master
  provider: bintray
  file: "bintray.data"
  user: alby128
  key:
    secure: "Il+kmdBfbwNOyeD05eaczLy/9IrZCnLpxoB6LeExXiBbwJdhXR+HDj4f6jGAMN69U3KdT+I0KWlzynTsRPq5qwPncwdZuxX2tBAB0RE/QY2GsabzZKB0jOkmQKZTySVnIptUEZRUN755rk/KYXuojpCl6/A5xlgYF7OVHFRZLahTvsaQGblnBQrn5Gwv9u8ORFLW6UzhaxlrDQwEgQ0wPPeVvyK6tl7w1PdJmxnLmZMcF28zoELeuL4OhSByon40qkPrmcxNA/2o4DUKFkDgv+5ztrGjZXsFiBcyCRuf4GGWBMzI0trV1hkYuRICUGN0LIczMwbm3S37TCRTuBQF/b+XF2cMKQU1hU51H9yk46fhOdoQJVYWvta+Wu+kKE4taT+pdnldxrPnF+oMlz+CCpIce/Qo1YewTxy8P0NBXdvfq0yhshv4x4gJ3iBnz+V23cE+FJ3HYy3nf5Xtmu+pQdR3OOwDNsmemm1Rk/jYCXIYm4kwSKAVZdF6pY6Zt2v7gYGBlMcPwHHYktA2WzKHIBKRYsk3WCEG/PoAORA0fCgqLVS4V3Lm7gH1a0W16U0rHuZTzBrV6Xe5SQZXxnASH/PKMrJWLfXBSCkswyLqsEycj+OG1RjcoFBvgsEjq4MwtDSOeVBxc27ZwEtFZ4/cl5hS8FFFAwsAp8nv+XI6coU="

after_deploy:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- brew bottle --verbose --merge --write ./*.json
- cd $(brew --repo albertosottile/syncplay)
- export OLD_MSG="$(git log --format=%B -n1)"
- git commit --amend -m"${OLD_MSG}" -m"[ci skip]"
- git show --name-status
- git remote rm origin
- git remote add origin https://albertosottile:${GH_TOKEN}@github.com/albertosottile/homebrew-syncplay.git > /dev/null 2>&1
- git push origin master --quiet