language: objective-c
osx_image: xcode8.3

branches:
  only:
  - test

script:
- brew install --verbose albertosottile/syncplay/pyside
- brew test --verbose albertosottile/syncplay/pyside

before_install:
- brew update
- brew upgrade python
- which python3
- python3 --version
- which pip3
- pip3 --version

install:
- brew install --only-dependencies albertosottile/syncplay/pyside
